using System.Collections.Generic;

namespace NutzCode.MPVPlayer.WPF.Wrapper.Models
{

    public class Language
    {
        public static List<Language> Languages = new List<Language>()
        {
            new Language(@"Abkhazian", "ab", "abk"),
            new Language(@"Afar", "aa", "aar"),
            new Language(@"Afrikaans", "af", "afr"),
            new Language(@"Akan", "ak", "aka"),
            new Language(@"Albanian", "sq", "sqi"),
            new Language(@"Amharic", "am", "amh"),
            new Language(@"Arabic", "ar", "ara"),
            new Language(@"Aragonese", "an", "arg"),
            new Language(@"Assamese", "as", "asm"),
            new Language(@"Armenian", "hy", "hye"),
            new Language(@"Avaric", "av", "ava"),
            new Language(@"Avestan", "ae", "ave"),
            new Language(@"Aymara", "ay", "aym"),
            new Language(@"Azerbaijani", "az", "aze"),
            new Language(@"Bashkir", "ba", "bak"),
            new Language(@"Bambara", "bm", "bam"),
            new Language(@"Basque", "eu", "eus"),
            new Language(@"Belarusian", "be", "bel"),
            new Language(@"Bengali", "bn", "ben"),
            new Language(@"Bihari languages", "bh", "bih"),
            new Language(@"Bislama", "bi", "bis"),
            new Language(@"Bosnian", "bs", "bos"),
            new Language(@"Breton", "br", "bre"),
            new Language(@"Bulgarian", "bg", "bul"),
            new Language(@"Burmese", "my", "mya"),
            new Language(@"Catalan", "ca", "cat"),
            new Language(@"Chamorro", "ch", "cha"),
            new Language(@"Chechen", "ce", "che"),
            new Language(@"Nyanja", "ny", "nya"),
            new Language(@"Chinese", "zh", "chi"),
            new Language(@"Chinese", "zh", "zho"),
            new Language(@"Chuvash", "cv", "chv"),
            new Language(@"Cornish", "kw", "cor"),
            new Language(@"Corsican", "co", "cos"),
            new Language(@"Cree", "cr", "cre"),
            new Language(@"Croatian", "hr", "hrv"),
            new Language(@"Czech", "cs", "ces"),
            new Language(@"Danish", "da", "dan"),
            new Language(@"Dhivehi", "dv", "div"),
            new Language(@"Dzongkha", "dz", "dzo"),
            new Language(@"English", "en", "eng"),
            new Language(@"Esperanto", "eo", "epo"),
            new Language(@"Estonian, eesti keel", "et", "est"),
            new Language(@"Ewe", "ee", "ewe"),
            new Language(@"Faroese", "fo", "fao"),
            new Language(@"Fijian", "fj", "fij"),
            new Language(@"Finnish", "fi", "fin"),
            new Language(@"French", "fr", "fra"),
            new Language(@"Fulah", "ff", "ful"),
            new Language(@"Galician", "gl", "glg"),
            new Language(@"German", "de", "deu"),
            new Language(@"Modern greek", "el", "ell"),
            new Language(@"Guarani", "gn", "grn"),
            new Language(@"Gujarati", "gu", "guj"),
            new Language(@"Haitian", "ht", "hat"),
            new Language(@"Hausa", "ha", "hau"),
            new Language(@"Hebrew", "he", "heb"),
            new Language(@"Herero", "hz", "her"),
            new Language(@"Hindi", "hi", "hin"),
            new Language(@"Hiri motu", "ho", "hmo"),
            new Language(@"Hungarian", "hu", "hun"),
            new Language(@"Interlingua", "ia", "ina"),
            new Language(@"Indonesian", "id", "ind"),
            new Language(@"Interlingue", "ie", "ile"),
            new Language(@"Irish", "ga", "gle"),
            new Language(@"Igbo", "ig", "ibo"),
            new Language(@"Sichuan yi", "ii", "iii"),
            new Language(@"Inupiaq", "ik", "ipk"),
            new Language(@"Ido", "io", "ido"),
            new Language(@"Icelandic", "is", "isl"),
            new Language(@"Icelandic", "is", "ice"),
            new Language(@"Italian", "it", "ita"),
            new Language(@"Inuktitut", "iu", "iku"),
            new Language(@"Japanese", "ja", "jpn"),
            new Language(@"Javanese", "jv", "jav"),
            new Language(@"Georgian", "ka", "kat"),
            new Language(@"Kongo", "kg", "kon"),
            new Language(@"Kikuyu", "ki", "kik"),
            new Language(@"Kuanyama", "kj", "kua"),
            new Language(@"Kazakh", "kk", "kaz"),
            new Language(@"Kalaallisut", "kl", "kal"),
            new Language(@"Kentral khmer", "km", "khm"),
            new Language(@"Kannada", "kn", "kan"),
            new Language(@"Korean", "ko", "kor"),
            new Language(@"Kanuri", "kr", "kau"),
            new Language(@"Kashmiri", "ks", "kas"),
            new Language(@"Kurdish", "ku", "kur"),
            new Language(@"Komi", "kv", "kom"),
            new Language(@"Kirghiz", "ky", "kir"),
            new Language(@"Latin", "la", "lat"),
            new Language(@"Luxembourgish", "lb", "ltz"),
            new Language(@"Ganda", "lg", "lug"),
            new Language(@"Limburgan", "li", "lim"),
            new Language(@"Lingala", "ln", "lin"),
            new Language(@"Lao", "lo", "lao"),
            new Language(@"Lithuanian", "lt", "lit"),
            new Language(@"Luba-katanga", "lu", "lub"),
            new Language(@"Latvian", "lv", "lav"),
            new Language(@"Malagasy", "mg", "mlg"),
            new Language(@"Marshallese", "mh", "mah"),
            new Language(@"Manx", "gv", "glv"),
            new Language(@"Maori", "mi", "mri"),
            new Language(@"Macedonian", "mk", "mkd"),
            new Language(@"Malayalam", "ml", "mal"),
            new Language(@"Mongolian", "mn", "mon"),
            new Language(@"Marathi", "mr", "mar"),
            new Language(@"Malay", "ms", "msa"),
            new Language(@"Maltese", "mt", "mlt"),
            new Language(@"Nauru", "na", "nau"),
            new Language(@"Norsk bokmål", "nb", "nob"),
            new Language(@"North ndebele", "nd", "nde"),
            new Language(@"Nepali", "ne", "nep"),
            new Language(@"Ndonga", "ng", "ndo"),
            new Language(@"Dutch", "nl", "nld"),
            new Language(@"Norwegian nynorsk", "nn", "nno"),
            new Language(@"Norwegian", "no", "nor"),
            new Language(@"South ndebele", "nr", "nbl"),
            new Language(@"Navajo", "nv", "nav"),
            new Language(@"Occitan", "oc", "oci"),
            new Language(@"Ojibwa", "oj", "oji"),
            new Language(@"Church slavic", "cu", "chu"),
            new Language(@"Oromo", "om", "orm"),
            new Language(@"Oriya", "or", "ori"),
            new Language(@"Ossetian", "os", "oss"),
            new Language(@"Panjabi", "pa", "pan"),
            new Language(@"Pali", "pi", "pli"),
            new Language(@"Persian", "fa", "fas"),
            new Language(@"Polish", "pl", "pol"),
            new Language(@"Pushto", "ps", "pus"),
            new Language(@"Portuguese", "pt", "por"),
            new Language(@"Quechua", "qu", "que"),
            new Language(@"Romansh", "rm", "roh"),
            new Language(@"Rundi", "rn", "run"),
            new Language(@"Romanian", "ro", "ron"),
            new Language(@"Russian", "ru", "rus"),
            new Language(@"Kinyarwanda", "rw", "kin"),
            new Language(@"Sanskrit", "sa", "san"),
            new Language(@"Sardu", "sc", "srd"),
            new Language(@"Sardinian", "sd", "snd"),
            new Language(@"Northern sami", "se", "sme"),
            new Language(@"Samoan", "sm", "smo"),
            new Language(@"Sango", "sg", "sag"),
            new Language(@"Serbian", "sr", "srp"),
            new Language(@"Scottish gaelic", "gd", "gla"),
            new Language(@"Shona", "sn", "sna"),
            new Language(@"Sinhala", "si", "sin"),
            new Language(@"Slovak", "sk", "slk"),
            new Language(@"Slovenian", "sl", "slv"),
            new Language(@"Somali", "so", "som"),
            new Language(@"Southern sotho", "st", "sot"),
            new Language(@"Spanish", "es", "spa"),
            new Language(@"Sundanese", "su", "sun"),
            new Language(@"Swahili", "sw", "swa"),
            new Language(@"Swati", "ss", "ssw"),
            new Language(@"Swedish", "sv", "swe"),
            new Language(@"Tamil", "ta", "tam"),
            new Language(@"Telugu", "te", "tel"),
            new Language(@"Tajik?", "tg", "tgk"),
            new Language(@"Thai", "th", "tha"),
            new Language(@"Tigrinya", "ti", "tir"),
            new Language(@"Tibetan", "bo", "bod"),
            new Language(@"Turkmen", "tk", "tuk"),
            new Language(@"Tagalog", "tl", "tgl"),
            new Language(@"Tswana", "tn", "tsn"), 
            new Language(@"Tonga", "to", "ton"),
            new Language(@"Turkish", "tr", "tur"),
            new Language(@"Tsonga", "ts", "tso"),
            new Language(@"Tatar?", "tt", "tat"),
            new Language(@"Twi", "tw", "twi"),
            new Language(@"Tahitian", "ty", "tah"),
            new Language(@"Uighur?", "ug", "uig"),
            new Language(@"Ukrainian", "uk", "ukr"),
            new Language(@"Urdu", "ur", "urd"),
            new Language(@"Uzbek", "uz", "uzb"),
            new Language(@"Venda", "ve", "ven"),
            new Language(@"Vietnamese", "vi", "vie"),
            new Language(@"Volapük", "vo", "vol"),
            new Language(@"Walloon", "wa", "wln"),
            new Language(@"Welsh", "cy", "cym"),
            new Language(@"Wolof", "wo", "wol"),
            new Language(@"Western Frisian", "fy", "fry"),
            new Language(@"Xhosa", "xh", "xho"),
            new Language(@"Yiddish", "yi", "yid"),
            new Language(@"Yoruba", "yo", "yor"),
            new Language(@"Zhuang", "za", "zha"),
            new Language(@"Zulu", "zu", "zul")
        };
        public string Name { get; set; }
        public string Code2 { get; set; }
        public string Code3 { get; set; }

        public Language(string name, string code2, string code3)
        {
            Name = name;
            Code2 = code2;
            Code3 = code3;
        }
    }
}
